restaurant/main/urls.py
from django.urls import path
from . import views

app_name = 'main'  # namespace

urlpatterns = [
    path('', views.index, name="index"),  # si menu/ donc rien apres alors utilise la view index
]

restaurant/menu/urls.py
from django.urls import path
from . import views


app_name = 'menu'  # namespace

urlpatterns = [
    path('', views.index, name="index"),  # si menu/ donc rien apres alors utilise la view index
]

restaurant/restaurant/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('menu/', include('menu.urls')),  # voit menu/ donc va au fichier menu/urls.py
    path('api/', include('menu.api_urls')), 
]

restaurant/main/models.py
from django.db import models


# Create your models here.
class IdentityStore(models.Model):
    nom = models.CharField(max_length=200)
    adresse = models.CharField(max_length=400)
    code_postal = models.CharField(max_length=200)
    ville = models.CharField(max_length=200)
    pays = models.CharField(max_length=200)
    telephone = models.CharField(max_length=400)



    def __str__(self):
        return self.nom  # pour utiliser le nom dans l'interface admin au lieu de pizza(1) ...

# on migre le model vers la bdd...
# python manage.py makemigrations
# resultat : no changes detected alors allez dans restaurant/settings.py
# rajoute :     'menu.apps.MenuConfig', dans INSTALLED_APPS
# puis il faut appliquer a la bdd :
#python manage.py migrate
# --------- A FAIRE SI CHANGEMENT DU MODEL DE LA BDD ------------
# créer la table d'association

restaurant/menu/models.py
from django.db import models


# Create your models here.
class Pizza(models.Model):
    nom = models.CharField(max_length=200)
    ingredients = models.CharField(max_length=400)
    prix = models.FloatField(default=0)
    vegetarienne = models.BooleanField(default=False)

    def __str__(self):
        return self.nom  # pour utiliser le nom dans l'interface admin au lieu de pizza(1) ...

# on migre le model vers la bdd...
# python manage.py makemigrations
# resultat : no changes detected alors allez dans restaurant/settings.py
# rajoute :     'menu.apps.MenuConfig', dans INSTALLED_APPS
# puis il faut appliquer a la bdd :
#python manage.py migrate
# --------- A FAIRE SI CHANGEMENT DU MODEL DE LA BDD ------------
# créer la table d'association

restaurant/main/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import IdentityStore

# Create your views here.

def index(request):
    # /main
    identity = IdentityStore.objects.all()
    # render(request, le html, les data a passer dans le html)
    return render(request, 'main/index.html', {'identity': identity})
    # return HttpResponse("home")

restaurant/menu/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.core import serializers
from .models import Pizza

def index(request):
    # /menu

    pizzas = Pizza.objects.all().order_by('prix')
    # render(request, le html, les data a passer dans le html)
    return render(request, 'menu/index.html', {'pizzas': pizzas})



# envoie des données pizzas en format json pour une api
# une fois fait aller dans urls.py
def api_get_pizzas(request):
    pizzas = Pizza.objects.all().order_by('prix')
    json = serializers.serialize("json", pizzas)
    return HttpResponse(json)

restaurant/main/templates/main/index.html
{% load static %}
<!-- pour les liens vers elements static voir link-->

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta name="viewport" content="width=device-width" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" href="{% static 'main/style.css' %}">
	<title>Pizza TEST - Acceuil</title>
</head>
<body>

    <main class="centered">
    <h1 id="main_title">PIZZA de chez TEST</h1>
    <img src="{% static 'main/images/main_logo.png' %}" alt="pizzeria TEST"></img>
    <a href="{% url 'menu:index' %}">Voir le menu</a>

    </main>

</body>
</html>

restaurant/menu/templates/menu/index.html
{% load static %}
<!-- pour les liens vers elements static voir link-->

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta name="viewport" content="width=device-width" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" href="{% static 'menu/style.css' %}">
	<title>Menu - Pizza MaMa</title>
</head>
<body>

    <a href="{% url 'main:index' %}">
        <img src="{% static 'menu/images/small_logo.png' %}" id="small_logo" alt="pizzeria MaMa"></img>
    </a>

    <header class="menu_title">
        <h1>Les pizzas</h1>
    </header>

    <main class="menu_list">

            {% for pizza in pizzas %} <!-- comme php le end a la fin-->

                    <div class="menu_list_item">
                        <span class="menu_list_title" >{{ pizza.nom }} : </span>
                        <span class="menu_list_prix" >{{ pizza.prix | floatformat:2 }} €</span>
                        <span class="menu_list_ingredients" > {{ pizza.ingredients}} </span>
                        {% if pizza.vegetarienne%}
                            <span class="menu_list_badge">Végétarienne</span>
                        {% endif%}
                    </div>

            {% endfor %}

    </main>

</body>
</html>